### ISSUE TITLE
Add Updated, Version and Developer

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Quadrapassel#1]
![Captura de tela de 2019-09-18 19-29-55](https://user-images.githubusercontent.com/26097419/65191572-c63f8f00-da4a-11e9-9a1b-6d430ce89371.png)

**Comment by bilelmoussaoui** [comment]
Should be fixed with the next minor release. See https://gitlab.gnome.org/GNOME/quadrapassel/merge_requests/14
