### ISSUE TITLE
Shows up twice in flatpak install

### ISSUE THREAD

**Issue by loganmc10** [flathub/org.gnome.Quadrapassel#7]
```
[loganmc10@rhel ~]$ flatpak install Quadrapassel
Looking for matches…
Similar refs found for ‘Quadrapassel’ in remote ‘flathub’ (system):

   1) app/org.gnome.Quadrapassel/x86_64/stable
   2) app/org.gnome.quadrapassel/x86_64/stable

Which do you want to use (0 to abort)? [0-2]
```

**Comment by hfiguiere** [comment]
because it is case sensitive.

It was renamed here.

https://github.com/flathub/org.gnome.Quadrapassel/commit/963bb190e4b03d0dae9fb4b4df6df05b61d223f2

**Comment by loganmc10** [comment]
It's still a little confusing for users isn't it? If the old name is decommissioned, why is it suggesting it for new installs?

**Comment by hfiguiere** [comment]
there is nothing the quadrapassel maintainers can do.

**Comment by hfiguiere** [comment]
It's a flatpak issue. https://github.com/flatpak/flatpak/issues/4834
